### ISSUE TITLE
panel should be (drag&drop) and floatable (3-5*)

### ISSUE THREAD

**Issue by neuling** [franzenzenhofer/f19n-livetest-chrome-extension#14]

**Comment by franzenzenhofer** [comment]
key von position soll von host abhängig sein 
toggle state bleibt bei tab

**Comment by neuling** [comment]
@franzenzenhofer ist jetzt mal in einer ersten version mit der vollen funktionalität umgesetzt. ist noch im branch [`floating-panel`](https://github.com/franzenzenhofer/f19n-livetest-chrome-extension/tree/floating-panel).

das panel sollte man nun weder durch resizing des browser oder durch verschieben des panels selbst über den rand des windows bekommen:

![o4tlzmcqkj](https://cloud.githubusercontent.com/assets/238180/17736690/86568ca2-6489-11e6-9c42-733e343f1ec3.gif)

die höhe passt sich an die höhe der liste an. wird jedoch maximal so hoch wie das window dann muss man scrollen:

![rlh6s6xwno](https://cloud.githubusercontent.com/assets/238180/17736739/c33b8532-6489-11e6-96d5-9f1cfacd1fd9.gif)

aktuelle todos:
- performance vom drag & drop selbst
- manchmal passt die höhe des iframes nicht (muss erst herausfinden wann und warum)

aktueller aufwand bis jetzt 3 arbeitsstunden. haben also noch bisschen buffer zum feintunen.

check den branch vielleicht mal aus und spiel dich damit herum wie es dir taugt. nochmal zur info, ich bin ab morgen bis inkl. 28 auf urlaub.

**Comment by franzenzenhofer** [comment]
hi morith, please see the other high prio issues. i like it - in the cases it works - and it's the only thing that I still need for submission  to the chrome extension store.

but the fact that the CSS now destroys most pages is a high prio bug that we need to fix
