### ISSUE TITLE
css leak

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#43]
![image](https://cloud.githubusercontent.com/assets/323190/18007082/d692eb46-6ba2-11e6-9a74-6082ddea3991.png)

on orf.at with the extension the text is now mini? is this a css leak?
@hg-lr please investigate and fix if it is

**Comment by neuling** [comment]
@franzenzenhofer sollte gefixed sein. bitte den branch `floating-panel` auschecken und auch nochmal testen.
