### ISSUE TITLE
floating panel is mini on tripadvisor

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#44]
![image](https://cloud.githubusercontent.com/assets/323190/18007143/12a60f5a-6ba3-11e6-9c02-517cac9c6f9f.png)

is: mini panel

should: panel should always be as long as possible within the viewport

**Comment by neuling** [comment]
@franzenzenhofer sollte gefixed sein. bitte den branch `floating-panel` auschecken und auch nochmal testen.
