### ISSUE TITLE
on veganblatt iframe and content is not on the same place

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#45]
![image](https://cloud.githubusercontent.com/assets/323190/18007187/4aac675a-6ba3-11e6-845c-942cccdbf368.png)

**Comment by neuling** [comment]
@franzenzenhofer sollte gefixed sein. bitte den branch `floating-panel` auschecken und auch nochmal testen.
