### ISSUE TITLE
Floating panel should be resizable

### ISSUE THREAD

**Issue by pixelution** [franzenzenhofer/f19n-livetest-chrome-extension#48]
All data should be visible without scrolling!

![image](https://cloud.githubusercontent.com/assets/2785869/19263615/73ab23ee-8f9d-11e6-82c3-533fc837026f.png)

**Comment by franzenzenhofer** [comment]
difficult: we don't know how much data we will have (don't know how many rules return something and how big the msg will be)

can prop be done with some JS, but still, what if you have 200 rules?

**Comment by pixelution** [comment]
Mhm, das ist schon klar, dass man Scrollbars nie ganz vermeiden kann.
Aber es wäre super wenn man die Höhe und Breite des Floating Panel per Drag & Drop anpassen könnte. Die wichtigsten Regeln sollten dann immer ohne Scrolling gleich sichtbar sein.
Ganz cool wäre natürlich noch wenn man eine Möglichkeit hätte die Reihenfolge der Regeln anzupassen - so könnte man sicherstellen, dass eine ganz wichtige Custom-Rule wirklich immer ohne Scrollen sofort sichtbar ist!?

**Comment by franzenzenhofer** [comment]
current solution good enough
