### ISSUE TITLE
MVP finish

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#49]
- [x] able to import rules 
- [x] (ideally: choose a (single) folder (rules still enable / disable / view))
- [x] new: no pre-check of rules anymore
- [x] new import rules / custom rules add further down (de-emphasizing of this feature)
- [x] upload with same rule as existing one should update the old one
- [x] view button for custom rules
- [x] no longer able to edit rules in browser (no new rule button, no duplicate rules, no edit)

- [x] new default position: right top (and snapped if at top right position)
- [x] default rules that were deleted (after app update) should vanish

- [x] change name of the extension to "Obtrusive Live Test" (change name of repository to "f19n-obtrusive-live-test"
- [x] general bug fixes

**Comment by franzenzenhofer** [comment]
hi moritz, added one thing

the official name of this extension is "Obtrusive Live Test"

if the old name "Obtrusive Livetest Chrome Extension" shows up anywhere visible, please change.

**Comment by neuling** [comment]
Panel should now snap to the corners of the browser. It also snaps to the bottom of the browser. What do you think @franzenzenhofer? Does it feel right? Can be disabled easily, just wanted to show it to you.

![71vjpbowa5](https://cloud.githubusercontent.com/assets/238180/23864237/2f9a1ab4-0812-11e7-8729-90383f65b5b2.gif)

**Comment by neuling** [comment]
Most of the new view-only rule concept is finished. Possibility to select/upload multiple rules. No pre-check per rule. Removed functionality to edit and duplicate rules. Removed the ability to add an empty rule. Removed some unused packages.

Todo: 
- [ ] Beautify Rule-View (Highlight code, display rule name and add close button) 
- [ ]  Move 'Add rule' down

![yn314xmbxv](https://cloud.githubusercontent.com/assets/238180/23869293/b6356d98-0822-11e7-865c-c644380df28d.gif)

**Comment by franzenzenhofer** [comment]
ad Panel should now snap to the corners of the browser

![mar-15-2017 10-41-55](https://cloud.githubusercontent.com/assets/323190/23942387/6ff32488-096c-11e7-9593-d34426441052.gif)

works and snapping to top and bottom right side is cool

but: now there is a lot of stuttering (see attachment) when moving around, if (easily) possible see if there is away to reduce this stuttering.

**Comment by franzenzenhofer** [comment]
custom rules should also have the view button

**Comment by franzenzenhofer** [comment]
ad jankink, passive event listeners?
https://blogs.windows.com/msedgedev/2017/03/08/scrolling-on-the-web/#ehgHAiKlb6YqOca2.97

**Comment by franzenzenhofer** [comment]
hmmm, adding rules with the same name should update the existing URL, not add another rule with the same name (this made sense when we had the editor in there, but with now just adding URLs it does not make sense any longer)

**Comment by neuling** [comment]
i did some debugging about the stuttering. the iframe inside the panel causes some performance issues. without the iframe it works perfectly. not sure how to fix this.

**Comment by neuling** [comment]
removed the ace editor from the view-rule view and added syntax highlighting. 

![unspecified-3](https://cloud.githubusercontent.com/assets/238180/24057695/88b34f38-0b48-11e7-9b43-3f65f4c7b49f.png)

**Comment by neuling** [comment]
add rule button is now underneath the "custom rule" section. what do you think @franzenzenhofer? for me, thats the most intuitive location for this button.

![unspecified-4](https://cloud.githubusercontent.com/assets/238180/24057882/5608db92-0b49-11e7-84ea-bbcc10952ab4.png)

**Comment by franzenzenhofer** [comment]
ad janking: not MVP critical, and yeah iframes are always an issue with rendering

**Comment by neuling** [comment]
unsupported rules should now be removed on install and/or extension update. to make sure the sync works also in production, we should test it once the extension is available on the chrome store.
