### ISSUE TITLE
rule configuration

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#50]
rule configuration

%GoogleApiKey%

leads to

GoogleApiKey: [                                                   ] 

rules that need a rule configuration are default disabled

**Comment by franzenzenhofer** [comment]
MVP prio low

but 

Feature prio high

**Comment by neuling** [comment]
i did a first quick implementation of this feature. you need to checkout the branch `configurable-rules` to test it.

here is a short demonstration: http://recordit.co/7uh5MzYIvQ

looking forward to your feedback. i think its pretty sweet but surely needs to be tested before we merge it into production.

**Comment by franzenzenhofer** [comment]
cool, will test tonight

**Comment by franzenzenhofer** [comment]
could not get it to work (click on rule does now show overlay)

but if it works, go ahead

**Comment by neuling** [comment]
k i will merge this branch into the master as soon as we have a solution for all the other issues.

**Comment by neuling** [comment]
merged into master!
