### ISSUE TITLE
resize panel in size 

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#51]
- [x] doc to right (remember per page)

**Comment by franzenzenhofer** [comment]
MVP prio high (the current default panel size is too small for the amount of rules already)

lets test this and if it makes sense for lots of pages, we make this the default

**Comment by neuling** [comment]
panel will auto adjust height respecting browser height (see gif). what do you think @franzenzenhofer?

![myucouf3n9](https://cloud.githubusercontent.com/assets/238180/24195203/1e1a563a-0ef9-11e7-9ace-ce6ba2877357.gif)

**Comment by franzenzenhofer** [comment]
i think it's awesome and definitely good enough MVP
