### ISSUE TITLE
background fetch accessible from rules

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#52]
this.fetch 

ignores cross origin headers

**Comment by franzenzenhofer** [comment]
PRIO feature medium

**Comment by neuling** [comment]
i did a quick test about the backgroundPage fetch thing and realised that due to the security policies of chrome we cannot break out of the sandbox page where all the rules gets evaluated. so there is no access to any chrome.* functions.

the only way to communicate with the backgroundPage is via postMessage (like we do it to run rules). downside: it's not as simple as initially thought. probably 1-2 hours of work.

**Comment by franzenzenhofer** [comment]
would be a necessary feature as I already now spammed the core logic with stuff that should not be in there (soft404 check, robots.txt check)

**Comment by franzenzenhofer** [comment]
done?

**Comment by neuling** [comment]
yes should be done.

**Comment by franzenzenhofer** [comment]
just a questions

```javascript
function(page, done) {
  this.fetch('https://orf.at', { responseFormat: 'text' }, (response) => {
    done(this.createResult('FETCH', `response from orf.at: ${response.length}`, 'info'));
  });
}
```

what is the syntax (is there a syntax) if fetch fails?

note: fetch works awesomly in src/public/default-rules/dom-detect-client-side-rendering.js

**Comment by neuling** [comment]
hm good question. what kind of errors would you like to catch? different http responses? or something like "net::ERR_NAME_NOT_RESOLVED" (website not reachable)?

**Comment by neuling** [comment]
in a perfect world i would pass the raw response from fetch as the first argument but since we communicate within iframes, i can only pass JSON around. so i need to catch all possible errors and uses cases on the chrome side of the extension and convert it to JSON.

**Comment by neuling** [comment]
here is the the interface where i run the actual fetch and return the response via postMessage to the sandbox:

```javascript
fetch(url, options || {}).then((response) => {
  response[responseFormat || 'text']().then((data) => {
    event.source.postMessage({ command: 'fetchResult', response: data, runId }, '*');
  });
});
```

**Comment by franzenzenhofer** [comment]
in a simple world i would just be happy if i get to know within the rule if the fetch failed (not even necessary to know why if this is the hard)

anyway / not necessary for MVP (but a note in the documentation would be a good idea)

**Comment by franzenzenhofer** [comment]
![image](https://cloud.githubusercontent.com/assets/323190/25453534/99f97b28-2ac9-11e7-9eb9-474d7c05d017.png)
a fetch now delives some meta information about the response, the response body is now in available in response.body

**Comment by neuling** [comment]
@franzenzenhofer awesome 👏

**Comment by neuling** [comment]
@franzenzenhofer let me know if this works for you so we can close this issue or if we need to iterate over it again.

**Comment by franzenzenhofer** [comment]
everythink OK, works great, error handling with status information good
enough (if fetch fails of other reasons not covered, but not critical)

**Comment by neuling** [comment]
k will close this issue. added as enhancement issue.
