### ISSUE TITLE
catch error output for async rules

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#53]
hi @neuling 

is there any way (or coding style in the async rules) to capture a failed rules similar as we do synchronous rules?

https://github.com/franzenzenhofer/f19n-livetest-chrome-extension/blob/master/src/javascripts/sandbox.js#L11-L13 

with synchronous rules if a rule fails (which can happen) we see the error output in the panel

while with async we only see in the in the background.html developer console.

is there way to do this, or do we need to implement this in the async rules with a try/fetch

note: no going down the rabbit hole, this debugging behaviour is not MVP critical

**Comment by franzenzenhofer** [comment]
PRIO feature low

**Comment by neuling** [comment]
@franzenzenhofer is this still an issue?

**Comment by franzenzenhofer** [comment]
nope
