### ISSUE TITLE
filtering should not resize panel

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#54]
is: filtering (lable, type) resizes the pane
should: filtering does not resize panel (as async rules might get missed)

**Comment by franzenzenhofer** [comment]
@neuling MVP prio HIGH (as it is a behaviour that we have, but does not work as intended)

**Comment by neuling** [comment]
hmm not sure if the resizing is the actual problem. it seems like that when i filter for something all Pending results will be removed and reevaluated after some time? i probably need to dig into your async rules implementation to fix this problem.

pls give me some more input on this issue before i start investigating in the wrong direction.

**Comment by franzenzenhofer** [comment]
hi, i would really just evaluate the resize behaviour (other you found an issue I don't see)

![mar-22-2017 12-29-08](https://cloud.githubusercontent.com/assets/323190/24195746/4d53e400-0efb-11e7-9e3f-f9151694d13e.gif)

**Comment by neuling** [comment]
oh, got it. interesting … can't reproduce this error. maybe #51 fixed this error to. pls pull, rebuild, reload and test if it still happen.

**Comment by franzenzenhofer** [comment]
is fixed
