### ISSUE TITLE
hiding the app (via click on x or icon in chrome bar) should stop executing rules

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#55]
if i visit pages and the app is hidden, no rules should get executed. showing the app should force reload the page.

**Comment by franzenzenhofer** [comment]
MVP prio medium

some of the rules have massive impact on browser ressources - so yeah, if we hide the app, the rules should not get executed

**Comment by neuling** [comment]
done in https://github.com/franzenzenhofer/f19n-livetest-chrome-extension/commit/03d63ef8b4fac4b10a3bde1e701606fb68c4eca1

the event collector will no longer catch events and execute rules for hidden panels. opening a previously hidden panel will reload the tab.
