### ISSUE TITLE
view rule code overlay can not be bigger as screen 

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#59]
i.e. speed-page-speed-insights-desktop-async.js rule

![image](https://cloud.githubusercontent.com/assets/323190/24623766/e0b939c2-18a9-11e7-8b19-c37ededa471e.png)

**Comment by neuling** [comment]
should be fixed.

![odov1k995h](https://cloud.githubusercontent.com/assets/238180/24652801/7b452a26-1933-11e7-97c9-05dd641f713c.gif)
